language: csharp
os: linux
mono: none
dist: xenial
dotnet: 3.1
branches:
  only:
    - master
services: mongodb
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build.sh
  - ./scripts/dotnet-test.sh
  - ./scripts/docker-publish.sh
notifications:
  email:
    on_success: never
    on_failure: always