@url = http://localhost:5000
@productId = 00000000-0000-0000-0000-000000000000

###
GET {{url}}/products/{{productId}}

###
GET {{url}}/products?priceFrom=30&priceTo=45

###
POST {{url}}/products
Content-Type: application/json

{
  "productId": "{{productId}}",
  "name": "Product name",
  "price": 34.99
}

###
DELETE {{url}}/products/{{productId}}

###
PUT {{url}}/products/{{productId}}
Content-Type: application/json

{
  "productId": "{{productId}}",
  "name": "New product name",
  "price": 29.99
}